version: "3.7"

services:
  postgresql:
    image: "bitnami/postgresql:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: orbeo
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
